# Generated by Django 4.2.3 on 2023-08-02 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('code', models.CharField(blank=True, max_length=6)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_team_spaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SU', 'superuser'), ('AD', 'admin'), ('NA', 'non-admin')], default='NA', max_length=2)),
                ('is_verified', models.BooleanField(blank=True, default=False)),
                ('nickname', models.CharField(max_length=16)),
                ('team_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.teamspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_team_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team_space', 'user')},
            },
        ),
    ]
