# Generated by Django 4.2.3 on 2023-08-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='has_been_edited',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='has_been_edited',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
