# Generated by Django 4.2.3 on 2023-08-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='nickname',
        ),
    ]
