# Generated by Django 4.2.3 on 2023-08-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_has_been_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='description',
            field=models.CharField(max_length=64),
        ),
    ]
