# Generated by Django 4.2.3 on 2023-08-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_member_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamspace',
            name='code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
