# Generated by Django 4.2.3 on 2023-08-03 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_teamspace_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamspace',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
