# Generated by Django 4.2.3 on 2023-08-05 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_ticket_end_date_alter_ticket_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
