# Generated by Django 4.2.3 on 2023-08-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
